#!/bin/bash

version_output() {
	echo "C-Template is a small tool that generates a ready-to-use C project"

	echo "Version 1.4.0"
	echo "Please donate to the EFF if this program has been of any help"
	echo ""
	echo "Copyright © 2026 tpalmerstudios"
	echo "License GPLv3+: GNU GPL version 3 or later https://gnu.org/licenses/gpl.html."
	echo "This is free software: you are free to change and redistribute it."
	echo "There is NO WARRANTY, to the extent permitted by law."
	echo ""
	echo "Written by tpalmerstudios"
}

help_output() {
	echo "Usage ./template-setup.sh [OPTION]"
	echo "Install a stub C Project to a sister directory"
	echo ""
	echo "-v, --version		output version information and exit"
	echo "-h, --help		display this help and exit"
	echo "    --no-git		skips all setup related to a git repository"
	echo "    --force		uses a directory even if it already exists. does not empty it first"
	echo "    --remove		removes a directory COMPLETELY before creating the template files in that directory"
	echo ""
	echo "Documentation <https://github.com/tpalmerstudios/c-template>"
	echo "Questions for the author: <obsoleteTiger@protonmail.com>"
}

force=false
version=false
remove=false
do_git=true
show_help=false

for param in "$@"; do
	case $param in
	--version | -v)
		version=true
		;;
	--force)
		force=true
		;;
	--remove)
		remove=true
		;;
	--no-git)
		do_git=false
		;;
	--help | -h | help)
		show_help=true
		;;
	*)
		echo "Unknown Option: $param"
		exit 1
		;;
	esac
done

if [ "$version" = true ]; then
	version_output
	exit 0
fi

if [ "$show_help" = true ]; then
	help_output
	exit 0
fi

read -p "Project Name: " proj_readable

proj_command=${proj_readable//[^[:alnum:] ]/}
proj_command=${proj_command//[[:space:]]/_}
proj_upper=${proj_command^^}

read -r -p "Project description. 1-2 Sentences don't use \\ or \/ or \|: " proj_description

proj_description=${proj_description//\\/\\\\}
proj_description=${proj_description//\"/\\\"}
proj_description=${proj_description//\$/\\\$}
proj_description=${proj_description//;/\\;}

echo "${proj_readable}"
echo "${proj_upper}"
echo "${proj_command}"
echo "${proj_description}"
read -p "Confirm Variables make sense (y/N): " confirm
if [[ "${confirm}" != "y" && "${confirm}" != "Y" ]]; then
	echo "Nothing Done... Exiting!"
	exit 1
fi

if [ "$remove" = true ] && [ -d "../$proj_command" ]; then
	echo "Removing the directory: '../$proj_command'"
	read -p "Type the name of the directory to confirm. ($proj_command): " confirm_remove
	if [[ "${proj_command}" != "${confirm_remove}" ]]; then
		echo "Nothing Done... Exiting!"
		exit 1
	else
		rm -rf "../$proj_command"
		echo "Removed ../$proj_command"
	fi
fi

if [ -d "../$proj_command" ]; then
	echo "'../$proj_command' already exists."
	if [ "$force" = true ]; then
		echo "Using existing directory ../$proj_command due to --force"
	else
		echo "Use \"--force\" to overwrite."
		echo "Exiting"
		exit 1
	fi
fi

mkdir "../$proj_command" || exit 1
if [ "$do_git" = true ]; then
	git init "../$proj_command"
	mkdir "../$proj_command/.github" || exit 1
	cp_check ./.github/
	cp_check ./.gitignore
	echo "$proj_description" >../$proj_command/.git/description
fi

# child dir copy
if cp -r ./child/* "../$proj_command"; then
	echo "Copied 'child' to ../$proj_command"
	else
		echo "Failed to copy 'child'"
		exit 1
	fi

cd "../$proj_command"

find . -type f -exec sed -i "s|01PROJCMD|$proj_command|g" {} +
find . -type f -exec sed -i "s|01PROJTEMP|$proj_readable|g" {} +
find . -type f -exec sed -i "s|01PROJDESC|$proj_description|g" {} +
find . -type f -exec sed -i "s|01PROJUPPER|$proj_upper|g" {} +

if [ "$do_git" = true ]; then
	git add .
	git commit -m "initial commit; template generated by tpalmerstudios/c-template"
fi

echo "Project $proj_command set up successfully!"
echo "--------------------------------------------"
echo "Todo:"
echo "Create the repo on Github."
echo "Set origin and push."
echo "Update Version numbers"
echo "Start coding"
