#ifndef PROJECT_VERSION_H
#define PROJECT_VERSION_H

#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 1
#define PROJECT_VERSION_PATCH 6

#define PROJECT_VERSION "0.1.6"

#endif // PROJECT_VERSION_H
